- name: Install EXE Package on Windows
  hosts: windows
  tasks:
    - name: Install Software
      win_package:
        path: C:\Saurabh\test-packages\*.exe
        arguments: '/S'  # Silent installation argument
        state: present
      register: install_result

    - name: Check Installation Status
      debug:
        msg: "{{ install_result }}"
